/source/business-workflow/source/Energinet.DataHub.MarketData.Application/
/source/business-workflow/source/Energinet.DataHub.MarketData.ApplyDBMigrationsApp/
/source/business-workflow/source/Energinet.DataHub.MarketData.Domain/
/source/business-workflow/source/Energinet.DataHub.MarketData.EntryPoint/
/source/business-workflow/source/Energinet.DataHub.MarketData.Infrastructure/
/source/business-workflow/source/Energinet.DataHub.MarketData.IntegrationTests/
/source/business-workflow/source/Energinet.DataHub.MarketData.Tests/
/source/ingestion/source/Energinet.DataHub.Ingestion.Application/
/source/ingestion/source/Energinet.DataHub.Ingestion.Asynchronous.AzureFunction/
/source/ingestion/source/Energinet.DataHub.Ingestion.Domain/
/source/ingestion/source/Energinet.DataHub.Ingestion.Infrastructure/
/source/ingestion/source/Energinet.DataHub.Ingestion.Synchronous.AzureFunction/
/source/ingestion/source/Energinet.DataHub.Ingestion.Tests/
/source/shared/GreenEnergyHub/source/GreenEnergyHub.Json/
/source/shared/GreenEnergyHub/source/GreenEnergyHub.Json.Tests/
/source/shared/GreenEnergyHub/source/GreenEnergyHub.TestHelpers/
/source/shared/GreenEnergyHub/source/GreenEnergyHub.TestHelpers.Tests/
/source/shared/iso8601/GreenEnergyHub.Iso8601/
/source/shared/iso8601/GreenEnergyHub.Iso8601.Tests/
/source/shared/iso8601/GreenEnergyHub.Iso8601.Tests/TestPleaseDelete/
/source/shared/messaging/source/GreenEnergyHub.Messaging/
/source/shared/messaging/source/GreenEnergyHub.Messaging.Integration.ServiceCollection/
/source/shared/messaging/source/GreenEnergyHub.Messaging.Protobuf/
/source/shared/messaging/source/GreenEnergyHub.Messaging.Protobuf.Integration.ServiceCollection/
/source/shared/messaging/source/GreenEnergyHub.Messaging.Protobuf.Tests/
/source/shared/messaging/source/GreenEnergyHub.Messaging.Tests/
/source/shared/queues/source/GreenEnergyHub.Queues/
/source/shared/queues/source/GreenEnergyHub.Queues.AzureServiceBus/
/source/shared/queues/source/GreenEnergyHub.Queues.AzureServiceBus.Integration.ServiceCollection/
/source/shared/queues/source/GreenEnergyHub.Queues.Kafka/
/source/shared/queues/source/GreenEnergyHub.Queues.Kafka.Integration.ServiceCollection/
/source/shared/queues/source/GreenEnergyHub.Queues.Tests/
/source/shared/queues/source/GreenEnergyHub.Queues.ValidationReportDispatcher/
/source/soap-to-json-adapter/source/Energinet.DataHub.SoapAdapter.Application/
/source/soap-to-json-adapter/source/Energinet.DataHub.SoapAdapter.Domain/
/source/soap-to-json-adapter/source/Energinet.DataHub.SoapAdapter.EntryPoint/
/source/soap-to-json-adapter/source/Energinet.DataHub.SoapAdapter.Infrastructure/
/source/soap-to-json-adapter/source/Energinet.DataHub.SoapAdapter.Tests/
